(function(){if(Math.floor(dist/250)*250>checkpoint){checkpoint=Math.floor(dist/250)*250;sound("coin");burst(W*.34,ground-30,10);vibrateHill(45);}if(car.speed>1.2&&car.air<=0&&Math.random()<.18){burst(W*.30,ground+2,2);burst(W*.38,ground+2,2);}const terrainLoad=Math.min(1,Math.abs(slope)*2.4);const throttleLoad=gas*.35;const targetCompression=Math.min(12,terrainLoad*8+throttleLoad*3+(car.air<=0?0:2));car.compression+=(targetCompression-car.compression)*.18*dt;car.susp+=(targetCompression-car.susp)*.20*dt;car.susp*=Math.pow(.84,dt);car.tilt+=(gas*.018-brake*.022-slope*.018-car.tilt)*.12*dt;car.impact*=Math.pow(.72,dt);if(car.air<=0){const oldAngle=car.angle;car.angle+=(slope+car.tilt-car.angle)*.11*dt;car.impact=Math.min(1,Math.abs(car.angle-oldAngle)*2.5);if(car.impact>.35)camShake=Math.min(9,camShake+car.impact*8)}if(fuel<=0){fuel=0;gas=0;car.speed*=Math.pow(.985,dt);if(Math.abs(car.speed)<.03){dead=true;end(false);return;}}for(const p of fuelPickups){if(!p.got&&Math.abs(p.x-world-W*.28)<28){p.got=true;fuel=Math.min(100,fuel+35);vibrateHill(35);score+=40;sound("coin");burst(W*.28,gy(world)-35,14);}}for(const p of pickups){if(!p.got&&Math.abs(p.x-world-W*.28)<24){p.got=true;coins++;bankCoins++;hillCombo++;hillComboTimer=90;hillComboMax=Math.max(hillComboMax,hillCombo);vibrateHill(25);localStorage.setItem("geta_hill_coins",bankCoins);score+=25;sound("coin");burst(W*.28,gy(world)-28,12);}}
function hillClimb(){
 const box=document.getElementById("hillBox");if(!box)return;
 const vehicles=[{name:"🚙 Buggy",color:"#e63946",acc:.11,max:8.5,grip:.18},{name:"🛻 4x4",color:"#2a9d8f",acc:.095,max:7.3,grip:.22},{name:"🏎️ Sport",color:"#f4a261",acc:.135,max:9.5,grip:.14}]; const upgrades=[0,0,0].map((_,i)=>+(localStorage.getItem("geta_hill_upgrade_"+i)||0)); let bankCoins=+(localStorage.getItem("geta_hill_coins")||0); const savedStars=[0,1,2].map(i=>+(localStorage.getItem("geta_hill_stars_"+i)||0));
 const levels=[{name:"🌄 Green Hills",sky:"#55b7ff",ground:"#5c9d3e",goal:1500,water:false,tunnel:false},{name:"🌊 Mountain Lake",sky:"#62c8ff",ground:"#4f963b",goal:1800,water:true,tunnel:false},{name:"🌋 Canyon Tunnel",sky:"#ffb36b",ground:"#70452c",goal:2100,water:false,tunnel:true}];
 let hillMute=localStorage.getItem("geta_hill_mute")==="1"; let hillWeather=+(localStorage.getItem("geta_hill_weather")||0); let hillBestJump=+(localStorage.getItem("geta_hill_best_jump")||0), hillJump=0, hillMaxSpeed=0,camShake=0,camZoom=1,boost=100,hillMissionDone=false,hillCombo=0,hillComboTimer=0,hillComboMax=0,hillSpeedRecord=+(localStorage.getItem("geta_hill_speed_record")||0),hillStartCountdown=0,hillGoalFx=0; let vehicle=0,level=0,canvas,ctx,W=0,H=0,dpr=1,seed=Math.random()*10000,world=0,dist=0,coins=0,fuel=100,gas=0,brake=0,dead=false,last=0,raf,score=0,paused=false,checkpoint=0,wheelSpin=0,splash=0,landFx=0,lastAir=0,hitFx=0,particles=[],audio=null;
 const car={angle:0,speed:0,bounce:0,air:0,airAngle:0,susp:0,tilt:0,wheelL:0,wheelR:0,compression:0,impact:0}; let pickups=[]; let fuelPickups=[];
 function unlocked(i){return i===0||+localStorage.getItem("geta_hill_level_"+i)===1} 
 function hillTotalStars(){return savedStars.reduce((a,b)=>a+b,0)}
function hillProgressText(){return "⭐ "+hillTotalStars()+"/9 Sterne · 🪙 "+bankCoins+" Münzen"}
function hillChallenge(){
 const pool=[
  {t:"🪙 Münzjäger",d:"Sammle 15 Münzen",ok:()=>coins>=15,r:80},
  {t:"🚀 Geschwindigkeitsrausch",d:"Erreiche 8 m/s",ok:()=>vehicles[vehicle].max>=8&&car.speed>=8,r:60},
  {t:"🛬 Saubere Landung",d:"Lande nach einem Sprung",ok:()=>landFx>0,r:70}
 ];
 return pool[Math.floor((dist+vehicle+level)%pool.length)];
}
function choose(){
  box.innerHTML='<div class="hillSelect"><h2>🏁 GETA HILL CLIMB</h2><p>🚗 Berge · 🌊 Wasser · 🌋 Tunnel</p><div id="hillProgressTop" style="margin:8px 0;padding:7px 12px;border-radius:10px;background:#0003;font-weight:bold">⭐ "+hillProgressText()+"</div><button id="hillPlay" style="font-size:20px;padding:12px 30px;margin:8px">▶ PLAY</button><div id="hillSetup" style="display:none"><p>Wähle dein Fahrzeug</p><div id="hillGarage" style="margin:8px 0;padding:8px;border:2px solid #ffffff55;border-radius:12px;background:#0002"><b>🔧 GARAGE</b><div id="hillWallet">🪙 "+bankCoins+"</div><div id="hillStats">Motor ▰▰▱ · Grip ▰▰▱</div><button id="hillUpgrade">⬆ Upgrade <small>(kostenlos)</small></button></div><p>Wähle Strecke</p><div id="hillLevelProgress" style="font-size:13px;opacity:.9;margin:6px 0">⭐ Sterne zeigen deinen besten Abschluss</div><div class="hillCars">'+vehicles.map((v,i)=>'<button data-v="'+i+'">'+v.name+'<small>'+(i===0?"Ausgeglichen":i===1?"Stabil":"Schnell")+'</small></button>').join("")+'</div><div class="hillLevels">'+levels.map((l,i)=>{const s=savedStars[i]||0;return '<button data-l="'+i+'" '+(!unlocked(i)?'disabled':'')+'>'+l.name+'<small>'+l.goal+' m · '+(s?("⭐".repeat(s)+"☆".repeat(3-s)):("☆☆☆"))+(unlocked(i)?'':' 🔒')+'</small></button>'}).join("")+'</div></div></div>';
  box.insertAdjacentHTML("afterbegin",'<div id="hillCountdownHud" style="position:absolute;left:50%;top:42%;transform:translate(-50%,-50%);font-size:64px;font-weight:900;color:#fff;text-shadow:0 4px 12px #000;z-index:60"></div>');'<div id="hillComboHud" style="position:absolute;left:50%;top:52px;transform:translateX(-50%);font-size:20px;font-weight:900;color:#ffd54a;text-shadow:0 2px 4px #000;z-index:30"></div>');box.insertAdjacentHTML("afterbegin",'<div id="hillBoostBar" style="position:absolute;right:8px;bottom:112px;width:110px;height:10px;border:2px solid #fff8;border-radius:8px;background:#0008;overflow:hidden;z-index:25"><div id="hillBoostFill" style="height:100%;width:100%;background:#ff9800"></div></div>');box.insertAdjacentHTML("afterbegin",'<button id="hillWeatherBtn" style="position:absolute;left:52px;top:8px;padding:7px 10px;border-radius:10px;border:1px solid #fff5;background:#0005;color:#fff;z-index:20">☀️</button>');box.querySelector("#hillWeatherBtn").onclick=()=>{hillWeather=(hillWeather+1)%4;localStorage.setItem("geta_hill_weather",hillWeather);box.querySelector("#hillWeatherBtn").textContent=["☀️","🌅","🌧️","🌙"][hillWeather]};box.insertAdjacentHTML("afterbegin",'<button id="hillFullscreen" style="position:absolute;left:8px;top:8px;padding:7px 10px;border-radius:10px;border:1px solid #fff5;background:#0005;color:#fff;z-index:20">⛶</button>');box.querySelector("#hillFullscreen").onclick=()=>{try{if(!document.fullscreenElement)box.requestFullscreen();else document.exitFullscreen()}catch(e){}};box.insertAdjacentHTML("afterbegin",'<button id="hillSound" style="position:absolute;right:8px;top:8px;padding:7px 10px;border-radius:10px;border:1px solid #fff5;background:#0005;color:#fff">🔊</button>');box.querySelector("#hillSound").onclick=()=>{hillMute=!hillMute;localStorage.setItem("geta_hill_mute",hillMute?"1":"0");box.querySelector("#hillSound").textContent=hillMute?"🔇":"🔊"};box.insertAdjacentHTML("afterbegin",'<button id="hillStatsBtn" style="position:absolute;right:62px;top:8px;padding:7px 10px;border-radius:10px;border:1px solid #fff5;background:#0005;color:#fff;z-index:20">🏆</button>');
box.querySelector("#hillStatsBtn").onclick=()=>{
 const high=+(localStorage.getItem("geta_hill_high")||0),jump=+(localStorage.getItem("geta_hill_best_jump")||0);
 box.insertAdjacentHTML("beforeend",'<div id="hillStatsPanel" style="position:absolute;inset:15%;padding:20px;border-radius:18px;background:#111e;color:#fff;text-align:center;z-index:50"><h2>🏆 REKORDE</h2><p>🏁 Streckenrekord: <b>'+high+'</b></p><p>🚀 Höchstgeschwindigkeit: <b>'+hillSpeedRecord.toFixed(1)+'</b></p><p>🛫 Längster Sprung: <b>'+jump.toFixed(1)+' m</b></p><p>⭐ Sterne: <b>'+hillTotalStars()+'/9</b></p><p>🪙 Münzen: <b>'+bankCoins+'</b></p><button id="hillStatsClose">Schließen</button></div>');
 box.querySelector("#hillStatsClose").onclick=()=>box.querySelector("#hillStatsPanel")?.remove();
};box.insertAdjacentHTML("afterbegin",'<button id="hillBoost" style="position:absolute;right:8px;bottom:62px;padding:10px 14px;border-radius:14px;border:2px solid #fff8;background:#f90;color:#111;font-weight:bold;z-index:25">🚀 BOOST</button>');
box.querySelector("#hillBoost").onpointerdown=()=>boosting=true;
box.querySelector("#hillBoost").onpointerup=()=>boosting=false;
box.querySelector("#hillBoost").onpointercancel=()=>boosting=false;box.querySelector("#hillPlay").onpointerdown=()=>{sound("start");const s=box.querySelector("#hillSetup");s.style.display="block";box.querySelector("#hillPlay").style.display="none"};
  box.querySelectorAll("[data-v]").forEach(b=>b.onpointerdown=()=>{vehicle=+b.dataset.v;refresh()});
  box.querySelectorAll("[data-l]").forEach(b=>b.onpointerdown=()=>{level=+b.dataset.l;refresh()});
  function refresh(){const u=upgrades[vehicle];const w=box.querySelector("#hillWallet");if(w)w.textContent="🪙 "+bankCoins;const st=box.querySelector("#hillStats");if(st)st.innerHTML="Motor "+"▰".repeat(Math.min(5,2+u))+"▱".repeat(Math.max(0,3-u))+" · Grip "+"▰".repeat(Math.min(5,2+u))+"▱".repeat(Math.max(0,3-u))+"<br><small>Stufe "+u+"/3 · Verbesserte Leistung</small>";box.querySelectorAll("[data-v]").forEach(x=>x.classList.toggle("selected",+x.dataset.v===vehicle));box.querySelectorAll("[data-l]").forEach(x=>x.classList.toggle("selected",+x.dataset.l===level))}
  refresh();const pt=box.querySelector("#hillProgressTop");if(pt)pt.textContent=hillProgressText(); box.querySelector("#hillUpgrade").onpointerdown=()=>{const u=upgrades[vehicle],cost=[0,100,250][u];if(u<3&&bankCoins>=cost){bankCoins-=cost;localStorage.setItem("geta_hill_coins",bankCoins);upgrades[vehicle]++;localStorage.setItem("geta_hill_upgrade_"+vehicle,upgrades[vehicle]);vehicles[vehicle].acc+=.012;vehicles[vehicle].max+=.35;vehicles[vehicle].grip+=.012;refresh();sound("coin")}};
  box.querySelectorAll("[data-v]").forEach(b=>b.onpointerdown=()=>{vehicle=+b.dataset.v;refresh()});
  box.querySelectorAll("[data-l]").forEach(b=>b.onpointerdown=()=>{level=+b.dataset.l;start()});
 }
 function makeFuelPickups(){fuelPickups=[];for(let x=320;x<levels[level].goal;x+=260+Math.random()*180)fuelPickups.push({x,got:false});} function makePickups(){pickups=[];for(let x=180;x<levels[level].goal;x+=80+Math.random()*70)pickups.push({x,got:false,bob:Math.random()*6});} function noise(x){return Math.sin(x*.0017+seed)*.55+Math.sin(x*.0043+seed*1.7)*.25+Math.sin(x*.0091+seed*.31)*.12}
 function gy(x){
  let y=H*.70-noise(x)*H*.17-Math.sin(x*.0007+seed)*H*.07;
  if(level===1 && x>850&&x<1120)y=H*.67;
  return y
 }
 function resize(){if(!canvas)return;const r=box.getBoundingClientRect();W=Math.max(280,r.width);H=Math.max(220,r.height);dpr=Math.min(devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+"px";canvas.style.height=H+"px";ctx.setTransform(dpr,0,0,dpr,0,0)}
 function vibrateHill(ms){try{if(navigator.vibrate&&!hillMute)navigator.vibrate(ms)}catch(e){}}
function sound(type){if(hillMute)return;try{if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==="suspended")audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);const f=type==="hit"?90:type==="land"?130:type==="coin"?720:210;o.frequency.value=f;o.type=type==="hit"?"sawtooth":"sine";g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.13);o.start();o.stop(audio.currentTime+.14)}catch(e){}}function burst(px,py,n=8){for(let i=0;i<n;i++)particles.push({x:px,y:py,vx:(Math.random()-.5)*3,vy:-Math.random()*3-1,life:20+Math.random()*15})}function updateParticles(){for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx;p.y+=p.vy;p.vy+=.12;p.life--;if(p.life<=0)particles.splice(i,1);else{ctx.globalAlpha=p.life/35;ctx.fillStyle="#e7c27a";ctx.fillRect(p.x,p.y,3,3)}}ctx.globalAlpha=1}function circle(x,y,r,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}
 function drawHeadlights(){
 if(hillWeather!==3)return;
 const gx=W*.34, gy0=H*.58;
 ctx.save();
 ctx.globalCompositeOperation="lighter";
 const g=ctx.createRadialGradient(gx+28,gy0-8,2,gx+150,gy0-5,170);
 g.addColorStop(0,"rgba(255,245,190,.55)");g.addColorStop(.35,"rgba(255,245,190,.22)");g.addColorStop(1,"rgba(255,245,190,0)");
 ctx.fillStyle=g;
 ctx.beginPath();ctx.moveTo(gx+8,gy0-16);ctx.lineTo(gx+190,gy0-70);ctx.lineTo(gx+220,gy0+55);ctx.lineTo(gx+8,gy0+8);ctx.closePath();ctx.fill();
 ctx.restore();
 ctx.save();ctx.fillStyle="#fff8c8";ctx.shadowBlur=12;ctx.shadowColor="#fff1a8";
 ctx.beginPath();ctx.arc(gx+18,gy0-10,3,0,Math.PI*2);ctx.arc(gx+42,gy0-10,3,0,Math.PI*2);ctx.fill();ctx.restore();
}
function drawWeatherOverlay(t){
 ctx.save();
 if(hillWeather===1){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,"#ffb36b");g.addColorStop(1,"#ffe0a3");ctx.fillStyle=g;ctx.globalAlpha=.18;ctx.fillRect(0,0,W,H)}
 if(hillWeather===2){ctx.fillStyle="#6f8795";ctx.globalAlpha=.22;ctx.fillRect(0,0,W,H);ctx.strokeStyle="#d9eef5";ctx.globalAlpha=.45;ctx.lineWidth=1;
  for(let i=0;i<70;i++){const x=(i*83+t*.22)%W,y=(i*47+t*.65)%H;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-4,y+12);ctx.stroke()}
 }
 if(hillWeather===3){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,"#07142d");g.addColorStop(1,"#263a59");ctx.fillStyle=g;ctx.globalAlpha=.34;ctx.fillRect(0,0,W,H);ctx.globalAlpha=.8;ctx.fillStyle="#fff";for(let i=0;i<35;i++){const x=(i*97)%W,y=(i*53)%H;ctx.beginPath();ctx.arc(x,y,1.2,0,Math.PI*2);ctx.fill()}}
 ctx.restore();
}
function drawClouds(t){
  ctx.save();ctx.globalAlpha=.7;ctx.fillStyle="#fff";
  for(let i=0;i<7;i++){const cx=((i*190-(world*.08+t*.015))%(W+260))-130,cy=45+(i%3)*42;
   ctx.beginPath();ctx.arc(cx,cy,18,0,Math.PI*2);ctx.arc(cx+22,cy-8,25,0,Math.PI*2);ctx.arc(cx+48,cy,18,0,Math.PI*2);ctx.fill();
  }ctx.restore();
}
function drawFarMountains(t){
 ctx.save();ctx.globalAlpha=.55;
 const base=H*.55;
 for(let layer=0;layer<3;layer++){
  const par=.025+layer*.035;ctx.fillStyle=layer===0?"#8ab0c2":layer===1?"#7195a5":"#587b89";
  ctx.beginPath();ctx.moveTo(0,base+70);
  for(let x=-80;x<=W+120;x+=80){const px=x-(world*par%160);const peak=base-70-layer*18-35*Math.sin(x*.015+layer);ctx.lineTo(x,peak);ctx.lineTo(x+45,base+70)}
  ctx.lineTo(W,base+90);ctx.lineTo(0,base+90);ctx.fill();
 }ctx.restore();
}
function drawTrees(layer,par){for(let i=-1;i<18;i++){const tx=i*150-(world*par%150);const h=28+((i*37+level*19)%28);const gy0=gy(world+tx+W*.34);ctx.fillStyle=level===2?"#47382b":"#315f35";ctx.fillRect(tx,gy0-h*.55,5,h*.55);ctx.beginPath();ctx.moveTo(tx-18,gy0-h*.35);ctx.lineTo(tx+2,gy0-h);ctx.lineTo(tx+22,gy0-h*.35);ctx.fill();ctx.beginPath();ctx.moveTo(tx-15,gy0-h*.12);ctx.lineTo(tx+2,gy0-h*.72);ctx.lineTo(tx+19,gy0-h*.12);ctx.fill();}}function drawMountain(col,base,amp,scale,off){ctx.fillStyle=col;ctx.beginPath();ctx.moveTo(0,H);for(let sx=0;sx<=W;sx+=10)ctx.lineTo(sx,base-noise(world*scale+sx*scale+off)*amp);ctx.lineTo(W,H);ctx.fill()}
 function draw(){const t=performance.now();const shakeX=(Math.random()-.5)*camShake,shakeY=(Math.random()-.5)*camShake;ctx.save();ctx.translate(shakeX,shakeY);drawMountain(level===2?"#6b4b3b":"#79a6c9",H*.58,H*.16,.35,120);drawMountain(level===2?"#4b382e":"#477f63",H*.65,H*.12,.7,500);drawTrees(0,.18);const fuelPct=Math.max(0,Math.min(100,fuel));ctx.fillStyle="#0009";ctx.fillRect(12,12,142,24);ctx.fillStyle=fuelPct<20?"#e53935":"#f5c542";ctx.fillRect(43,17,100*fuelPct/100,14);ctx.fillStyle="#fff";ctx.font="bold 12px sans-serif";ctx.textAlign="left";ctx.fillText("⛽ "+Math.round(fuelPct)+"%",16,28);if(fuelPct<20){ctx.fillStyle="#fff";ctx.font="bold 14px sans-serif";ctx.fillText("⚠ LOW FUEL",12,55);}fuelPickups.forEach(p=>{if(!p.got){const sx=p.x-world+W*.28;if(sx>-25&&sx<W+25){const py=gy(p.x)-30;ctx.fillStyle="#f5f5f5";ctx.fillRect(sx-7,py-11,14,22);ctx.fillStyle="#d22";ctx.fillRect(sx-7,py-11,14,5);ctx.fillStyle="#333";ctx.fillRect(sx-3,py-7,6,12);ctx.fillStyle="#fff";ctx.font="bold 12px sans-serif";ctx.textAlign="center";ctx.fillText("F",sx,py+4);}}});pickups.forEach(p=>{if(!p.got){const sx=p.x-world+W*.28;if(sx>-20&&sx<W+20){const py=gy(p.x)-28+Math.sin(Date.now()/180+p.bob)*5;circle(sx,py,9,"#ffd54a");circle(sx,py,4,"#fff1a8");}}});
  const L=levels[level],sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,L.sky);sky.addColorStop(.62,"#d7f2ff");sky.addColorStop(1,"#eaf7d7");ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);
  circle(W*.78,H*.16,28,"#fff0a0");drawMountain(level===2?"#9b6545":"#a5c99e",H*.64,H*.13,.35,2000);drawMountain(level===2?"#70452c":"#70a968",H*.70,H*.15,.52,4000);
  const x=world+W*.34,ground=gy(x);
  ctx.beginPath();ctx.moveTo(0,H);for(let sx=0;sx<=W;sx+=7)ctx.lineTo(sx,gy(world+sx));ctx.lineTo(W,H);ctx.fillStyle=L.ground;ctx.fill();
  ctx.beginPath();ctx.moveTo(0,H);for(let sx=0;sx<=W;sx+=7)ctx.lineTo(sx,gy(world+sx)+8);ctx.lineTo(W,H);ctx.fillStyle=level===2?"#52321f":"#76502f";ctx.fill();
  if(level===1){const sx=850-world;if(sx<W&&sx+270>0){ctx.fillStyle="#2b9bd1";ctx.fillRect(sx,H*.67,270,H*.33);ctx.fillStyle="#b8edff";for(let wx=sx;wx<sx+270;wx+=35){ctx.beginPath();ctx.arc(wx,H*.68,14,Math.PI,0);ctx.fill()}}}
  if(level===1){const bx=850-world;ctx.fillStyle="#744b2d";for(let i=0;i<7;i++)ctx.fillRect(bx+i*42,H*.62,34,8);ctx.fillStyle="#4a3425";for(let i=0;i<7;i++)ctx.fillRect(bx+i*42,H*.62+8,5,40)}
  if(level===2){const tx=1250-world;ctx.fillStyle="#3b271d";ctx.beginPath();ctx.arc(tx+105,H*.71,105,Math.PI,0);ctx.fill();ctx.fillRect(tx,H*.71,210,H*.29);ctx.fillStyle="#17120f";ctx.beginPath();ctx.arc(tx+105,H*.71,78,Math.PI,0);ctx.fill();ctx.fillRect(tx+27,H*.71,156,H*.29)}
  for(let oi=0;oi<levels[level].goal/280;oi++){const ox=760+oi*280+(oi%3)*65,sx=ox-world;if(sx>-50&&sx<W+50){const oy=gy(ox)-14;ctx.save();ctx.translate(W*.34,ground-18+car.bounce+car.susp);ctx.rotate(car.angle);ctx.translate(-W*.34,-(ground-18+car.bounce+car.susp));ctx.save();ctx.translate(sx,oy);if(oi%3===0){ctx.fillStyle="#76502f";ctx.fillRect(-13,-13,26,26);ctx.strokeStyle="#c99558";ctx.strokeRect(-13,-13,26,26);ctx.beginPath();ctx.moveTo(-10,-10);ctx.lineTo(10,10);ctx.moveTo(10,-10);ctx.lineTo(-10,10);ctx.stroke()}else if(oi%3===1){circle(0,0,14,"#555");circle(0,0,8,"#222");}else{ctx.fillStyle="#777";ctx.beginPath();ctx.moveTo(-18,12);ctx.lineTo(-10,-12);ctx.lineTo(12,-15);ctx.lineTo(19,12);ctx.closePath();ctx.fill()}ctx.restore()}}
  for(let x0=650;x0<levels[level].goal*7;x0+=1050){const sx=x0-world;if(sx>-220&&sx<W+220){ctx.fillStyle="#9b6b3d";ctx.beginPath();ctx.moveTo(sx,gy(x0)+5);ctx.lineTo(sx+180,gy(x0+180)+5);ctx.lineTo(sx+90,gy(x0+90)-42);ctx.closePath();ctx.fill()}}
  for(let i=0;i<levels[level].goal/110;i++){const ix=430+i*110+(i%3)*35;if(ix<world-40||ix>world+W+40)continue;const iy=gy(ix)-25;if(i%7===0){ctx.fillStyle="#e33";ctx.fillRect(ix-world-9,iy-13,18,26);ctx.fillStyle="#fff";ctx.font="bold 10px sans-serif";ctx.textAlign="center";ctx.fillText("F",ix-world,iy+4)}else{circle(ix-world,iy,8,"#ffd83d");circle(ix-world,iy,4,"#f5ad18")}}
  const slope=Math.atan2(gy(x+22)-gy(x-22),44),cx=W*.34,cy=ground-25;if(car.air>0){lastAir=car.air;car.air-=1}else{if(lastAir>0){landFx=10;car.bounce=-5;burst(cx,cy+15,7);sound("land")}car.angle+=(slope-car.angle)*.16;car.airAngle=car.angle}
  car.bounce+=((Math.sin(performance.now()*.018)*Math.min(2,Math.abs(car.speed)*.3))-car.bounce)*.22;landFx=Math.max(0,landFx-.35);hitFx=Math.max(0,hitFx-.35);ctx.save();ctx.translate(cx,cy+car.bounce);ctx.rotate(car.airAngle);const v=vehicles[vehicle];
  ctx.strokeStyle="#333";ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-20,4);ctx.lineTo(-20,14);ctx.moveTo(20,4);ctx.lineTo(20,14);ctx.stroke();ctx.fillStyle=v.color;ctx.beginPath();ctx.roundRect(-30,-13,60,25,5);ctx.fill();ctx.fillStyle="#c9efff";ctx.beginPath();ctx.moveTo(-14,-13);ctx.lineTo(-4,-24);ctx.lineTo(12,-24);ctx.lineTo(19,-13);ctx.closePath();ctx.fill();circle(-19,13,10,"#222");circle(19,13,10,"#222");ctx.strokeStyle="#ddd";ctx.lineWidth=2;for(const wx of [-19,19]){ctx.save();ctx.translate(wx,13);ctx.rotate(wheelSpin);ctx.beginPath();ctx.moveTo(-5,0);ctx.lineTo(5,0);ctx.moveTo(0,-5);ctx.lineTo(0,5);ctx.stroke();ctx.restore()}ctx.fillStyle="#fff";ctx.font="bold 8px sans-serif";ctx.textAlign="center";ctx.fillText("GETA",0,2);if(hitFx>0){ctx.save();ctx.strokeStyle="#ffd43b";ctx.globalAlpha=Math.min(1,hitFx/8);ctx.font="bold 18px sans-serif";ctx.fillText("💥",cx+30,cy-20);ctx.restore()}if(landFx>0){ctx.save();ctx.strokeStyle="#fff";ctx.globalAlpha=Math.min(1,landFx/10);ctx.lineWidth=2;for(const wx of [-19,19]){ctx.beginPath();ctx.moveTo(cx+wx-7,cy+14);ctx.lineTo(cx+wx+7,cy+14);ctx.stroke()}ctx.restore()}ctx.restore();
  document.getElementById("hcDist").textContent=Math.floor(dist)+" m";document.getElementById("hcCoins").textContent="🪙 "+coins;document.getElementById("hcFuel").textContent="⛽ "+Math.max(0,Math.floor(fuel))+"%";document.getElementById("hcScore").textContent="⭐ "+Math.floor(score);document.getElementById("hcLevel").textContent=L.name+" · Checkpoint "+Math.floor(checkpoint)+"/"+L.goal+" m";
 }
 function end(msg){if(dead)return;dead=true;cancelAnimationFrame(raf);hillComboTimer=Math.max(0,hillComboTimer-dt);if(hillComboTimer<=0)hillCombo=0;score=Math.floor(dist)+coins*25+Math.max(0,hillCombo-1)*10;const old=+localStorage.getItem("geta_hill_high")||0;if(score>old)localStorage.setItem("geta_hill_high",score);if(msg.includes("Level geschafft")){hillGoalFx=1;localStorage.setItem("geta_hill_level_"+Math.min(2,level+1),1);const stars=score>levels[level].goal*.75?3:score>levels[level].goal*.45?2:1;savedStars[level]=Math.max(savedStars[level],stars);localStorage.setItem("geta_hill_stars_"+level,savedStars[level])}box.insertAdjacentHTML("beforeend",'<div class="hillResult"><strong>'+msg+'</strong><div>'+levels[level].name+' · '+vehicles[vehicle].name+'<br>🏁 Strecke: '+Math.floor(dist)+' m<br>🪙 Münzen: '+coins+'<br>⭐ Score: '+score+'<br>🏆 Rekord: '+Math.max(score,old)+'<br>⭐ Sterne: '+(score>levels[level].goal*.75?3:score>levels[level].goal*.45?2:1)+'/3</div><button id="hillRetry">🔄 Nochmal</button> <button id="hillMenu">🏠 Menü</button></div>');box.querySelector("#hillRetry").onclick=()=>start();box.querySelector("#hillMenu").onclick=()=>choose()}
 box.insertAdjacentHTML("afterbegin",'<div id="hillChallengeHud" style="position:absolute;left:50%;top:8px;transform:translateX(-50%);padding:6px 10px;border-radius:10px;background:#0006;color:#fff;font-size:12px;z-index:15"></div>');function start(){hillStartCountdown=90;const challenge=hillChallenge();hillMissionDone=false;const ch=box.querySelector("#hillChallengeHud");if(ch)ch.textContent="🎯 "+challenge.t+" · "+challenge.d;makePickups();makeFuelPickups();
  box.innerHTML='<canvas></canvas><div class="hillHud"><span id="hcLevel">'+levels[level].name+'</span><span id="hcDist">0 m</span><span id="hcCoins">🪙 0</span><span id="hcFuel">⛽ 100%</span><span id="hcScore">⭐ 0</span><button id="hcPause">⏸</button></div><div class="hillHint">◀ Bremsen &nbsp; ▶ Gas</div><div class="hillControls"><button id="hcBrake">◀</button><button id="hcGas">▶</button></div>';
  canvas=box.querySelector("canvas");ctx=canvas.getContext("2d");resize();addEventListener("resize",resize);const btn=(el,on)=>{el.onpointerdown=e=>{e.preventDefault();on(1)};el.onpointerup=el.onpointercancel=()=>on(0)};btn(box.querySelector("#hcGas"),v=>gas=v);btn(box.querySelector("#hcBrake"),v=>brake=v);box.querySelector("#hcPause").onpointerdown=e=>{e.preventDefault();paused=!paused;box.querySelector("#hcPause").textContent=paused?"▶":"⏸"};
  world=0;dist=0;coins=0;fuel=100;gas=0;brake=0;dead=false;score=0;paused=false;checkpoint=0;wheelSpin=0;car.angle=0;car.speed=0;car.air=0;car.airAngle=0;car.susp=0;car.tilt=0;boost=100;last=performance.now();loop(last)
 }
 function loop(now){if(!hillMissionDone&&challenge.ok()){hillMissionDone=true;localStorage.setItem("geta_hill_mission_done","1");bankCoins+=challenge.r;localStorage.setItem("geta_hill_coins",bankCoins);score+=challenge.r;vibrateHill(70);sound("coin");const ch=box.querySelector("#hillChallengeHud");if(ch)ch.textContent="✅ "+challenge.t+" +"+challenge.r+" 🪙";}const dt=Math.min((now-last)/16.67,2);if(hillStartCountdown>0)hillStartCountdown-=dt;camShake*=Math.pow(.78,dt);camZoom+=(1+Math.min(.10,Math.max(0,car.speed)/80)-camZoom)*.08*dt;last=now;if(dead)return;if(paused){const bf=box.querySelector("#hillBoostFill");if(bf)bf.style.width=boost+"%";const comboHud=box.querySelector("#hillComboHud");if(comboHud)comboHud.textContent=hillCombo>1?"🔥 COMBO x"+hillCombo:"";const cd=box.querySelector("#hillCountdownHud");if(cd)cd.textContent=hillStartCountdown>0?(hillStartCountdown>60?"3":hillStartCountdown>30?"2":"1"):"GO!";if(cd&&hillStartCountdown<=0){setTimeout(()=>{if(cd)cd.textContent=""},350);}ctx.restore();updateParticles();draw();if(splash>0&&level===1){ctx.save();ctx.strokeStyle="#dff";ctx.lineWidth=2;for(let i=0;i<8;i++){let px=W*.34-28+i*8,py=ground+8-(splash%4)*3;ctx.beginPath();ctx.moveTo(px,py);ctx.lineTo(px+(i%2?5:-5),py-12-(i%3)*4);ctx.stroke()}ctx.restore()}raf=requestAnimationFrame(loop);return;}const x=world+W*.34,slope=(gy(x+18)-gy(x-18))/36,v=vehicles[vehicle];car.speed+=gas*v.acc*dt-brake*.17*dt-slope*v.grip*dt;if(car.air>0){car.airAngle+=(gas-brake)*.035*dt;car.airAngle*=Math.pow(.995,dt)}car.speed*=Math.pow(.993,dt);car.speed=Math.max(-2.2,Math.min(v.max,car.speed));world+=Math.max(0,car.speed)*dt*2.55;dist=Math.max(dist,world/7);checkpoint=Math.max(checkpoint,Math.floor(dist/250)*250);wheelSpin+=car.speed*dt*.18;hillMaxSpeed=Math.max(hillMaxSpeed,car.speed);if(hillMaxSpeed>hillSpeedRecord){hillSpeedRecord=hillMaxSpeed;localStorage.setItem("geta_hill_speed_record",hillSpeedRecord.toFixed(2));}if(car.air>0){hillJump+=Math.max(0,car.speed)*dt*.12}else if(hillJump>0){hillBestJump=Math.max(hillBestJump,hillJump);localStorage.setItem("geta_hill_best_jump",hillBestJump.toFixed(1));hillJump=0;}car.wheelL=wheelSpin;car.wheelR=wheelSpin*(1+(slope*.08));splash=Math.max(0,splash-dt);fuel-=gas*.043*dt;if(boost>0&&gas>0&&boosting){car.speed+=.055*dt;boost-=.55*dt} else if(!boosting&&boost<100){boost=Math.min(100,boost+.08*dt)}score=Math.floor(dist)+coins*25;
  if(level===1&&x>830&&x<1140){splash=10;sound("water");if(Math.abs(car.angle)>1.2)end("🌊 Ins Wasser gerutscht!");}const obstacleIndex=Math.floor((x-760)/280);if(obstacleIndex>=0&&obstacleIndex<levels[level].goal/280&&Math.abs(x-(760+obstacleIndex*280+(obstacleIndex%3)*65))<38&&car.air<=0&&Math.abs(slope)<1.2){hitFx=8;car.speed*=.62;score=Math.max(0,score-10);burst(W*.34,ground,10);sound("hit");}if(level===2&&x>1260&&x<1450&&Math.abs(car.angle)>1.45)end("🪨 Im Tunnel überschlagen!");
  const r=Math.floor(x/1000);if(car.air<=0&&Math.abs(slope)>.55&&car.speed>4.5)car.air=22,car.airAngle=slope;
  if(Math.abs(car.airAngle)>1.62&&car.air>0)vibrateHill(180);end("💥 Überschlag in der Luft!");else if(Math.abs(car.angle)>1.55)vibrateHill(180);end("💥 Überschlag!");else if(fuel<=0)end("⛽ Benzin leer!");else if(dist>=levels[level].goal)end("🏆 Level geschafft!");
  draw();raf=requestAnimationFrame(loop)
 }
 choose()
}
window.hillClimb=hillClimb;
})();