let reactionTimer,reactReady=false,reactStart;
function reaction(){const box=document.getElementById("reactionResult");box.innerHTML='<button class="reactionBtn" disabled>Warte…</button>';reactReady=false;clearTimeout(reactionTimer);reactionTimer=setTimeout(()=>{reactReady=true;reactStart=performance.now();box.innerHTML='<button class="reactionBtn goBtn">🟢 JETZT!</button>';},1000+Math.random()*3000)}
document.addEventListener("click",e=>{if(reactReady&&e.target.classList.contains("goBtn")){const ms=Math.round(performance.now()-reactStart);document.getElementById("reactionResult").innerHTML='<strong>⚡ '+ms+' ms</strong><br><button onclick="reaction()">Nochmal</button>';reactReady=false}});
let spaceRun;
function space(){const b=document.getElementById("spaceBox");b.innerHTML='<div id="ship">🚀</div><div class="score" id="spaceScore">Score: 0</div><div class="spaceControls"><button data-dir="left">◀</button><button data-dir="right">▶</button></div>';const ship=b.querySelector("#ship");let score=0,x=50;function move(dir){x=dir==="left"?Math.max(8,x-8):Math.min(92,x+8);ship.style.left=x+"%"}b.querySelector('[data-dir="left"]').addEventListener("pointerdown",()=>move("left"));b.querySelector('[data-dir="right"]').addEventListener("pointerdown",()=>move("right"));document.onkeydown=e=>{if(e.key==="ArrowLeft")move("left");if(e.key==="ArrowRight")move("right")};clearInterval(spaceRun);spaceRun=setInterval(()=>{score++;document.getElementById("spaceScore").textContent="Score: "+score;if(score>=30){clearInterval(spaceRun);b.innerHTML='<strong>🏆 Überlebt! Score '+score+'</strong><br><button onclick="space()">Nochmal</button>'}},1000)}
function memory(){const r=document.getElementById("memoryResult");const a=["🍎","🚀","⭐","🐱","🍎","🚀","⭐","🐱"].sort(()=>Math.random()-.5);let open=[],done=0;r.innerHTML="";a.forEach(v=>{const b=document.createElement("button");b.className="memoryCard";b.textContent="❓";b.onclick=()=>{if(open.length>=2||b.dataset.done)return;b.textContent=v;open.push([b,v]);if(open.length===2){if(open[0][1]===open[1][1]){open.forEach(x=>x[0].dataset.done=1);done+=2;open=[];if(done===8)r.insertAdjacentHTML("beforeend","<p>🏆 Geschafft!</p>")}else setTimeout(()=>{open.forEach(x=>x[0].textContent="❓");open=[]},600)}};r.appendChild(b)})}
function aim(){const b=document.getElementById("aimBox");let n=0,start=performance.now();b.innerHTML='<div id="target"></div><div class="score" id="aimScore">0 / 10</div>';function next(){const t=document.getElementById("target");if(!t)return;t.style.left=Math.random()*78+"%";t.style.top=Math.random()*58+"%";t.onclick=()=>{n++;document.getElementById("aimScore").textContent=n+" / 10";if(n>=10){b.innerHTML="<strong>🎯 "+(Math.round((performance.now()-start))/1000).toFixed(3)+" s</strong><br><button onclick=\\"aim()\\">Nochmal</button>"}else next()}}next()}
let planeFrame,planeScore=0,planeY=50,planeAlive=false;
function flappy(){const b=document.getElementById("flappyBox");clearInterval(planeFrame);planeScore=0;planeY=50;planeAlive=true;b.innerHTML='<div class="flappyScore" id="flappyScore">Score: 0</div><div id="plane">✈️</div><div class="flappyHint">Tippen = hoch</div>';const plane=b.querySelector("#plane");let velocity=0,obstacles=[],last=performance.now(),spawn=0;
function flap(){if(planeAlive)velocity=-7}b.onpointerdown=flap;document.onkeydown=e=>{if(e.code==="Space"||e.key==="ArrowUp"){e.preventDefault();flap()}};function end(){planeAlive=false;clearInterval(planeFrame);b.innerHTML='<strong>💥 Game Over – Score '+planeScore+'</strong><br><button onclick="flappy()">Nochmal</button>'}
planeFrame=setInterval(()=>{const now=performance.now(),dt=Math.min((now-last)/16,2);last=now;velocity+=0.42*dt;planeY+=velocity*dt;if(planeY<5||planeY>92)return end();plane.style.top=planeY+"%";spawn-=dt;if(spawn<=0){spawn=65;const gap=42+Math.random()*8,gapTop=10+Math.random()*(78-gap);const top=document.createElement("div"),bottom=document.createElement("div");top.className=bottom.className="pipe";top.style.height=gapTop+"%";bottom.style.height=(100-gapTop-gap)+"%";bottom.style.bottom="0";bottom.style.top="auto";b.append(top,bottom);obstacles.push({top,bottom,x:100,passed:false})}obstacles.forEach(o=>{o.x-=0.9*dt;o.top.style.left=o.bottom.style.left=o.x+"%";const px=plane.offsetLeft,py=plane.offsetTop,pw=plane.offsetWidth,ph=plane.offsetHeight;const ox=o.top.offsetLeft,ow=o.top.offsetWidth;if(ox<px+pw&&ox+ow>px){const gapTopH=o.top.offsetHeight,gapBottomY=o.bottom.offsetTop;if(py<gapTopH||py+ph>gapBottomY)return end()}if(!o.passed&&o.x<0){o.passed=true;planeScore++;document.getElementById("flappyScore").textContent="Score: "+planeScore}});obstacles=obstacles.filter(o=>o.x>-12)},16)}
