function saveHigh(key,value,lower=false){try{const n=Number(value),old=Number(localStorage.getItem("geta_"+key)||"");if(!old||(lower?n<old:n>old)){localStorage.setItem("geta_"+key,String(n));return true}}catch(e){}return false}
function getHigh(key){try{return localStorage.getItem("geta_"+key)}catch(e){return null}}
function highText(key,unit){const v=getHigh(key);return v?'<div class="highscore">🏆 Rekord: '+v+(unit||"")+'</div>':'<div class="highscore">🏆 Noch kein Rekord</div>'}
function toggleFullscreen(btn){const article=btn.closest("article");if(!document.fullscreenElement){(article.requestFullscreen?article.requestFullscreen():article.webkitRequestFullscreen?.()).catch(()=>{});btn.textContent="⛶ Vollbild verlassen"}else{(document.exitFullscreen?document.exitFullscreen():document.webkitExitFullscreen?.());btn.textContent="⛶ Vollbild"}}
document.addEventListener("fullscreenchange",()=>{document.querySelectorAll(".fullscreenBtn").forEach(btn=>{btn.textContent=document.fullscreenElement===btn.closest("article")?"⛶ Vollbild verlassen":"⛶ Vollbild"});});
let reactionTimer,reactReady=false,reactStart;
function reaction(){const box=document.getElementById("reactionResult");box.innerHTML='<button class="reactionBtn" disabled>Warte…</button>';reactReady=false;clearTimeout(reactionTimer);reactionTimer=setTimeout(()=>{reactReady=true;reactStart=performance.now();box.innerHTML='<button class="reactionBtn goBtn">🟢 JETZT!</button>';},1000+Math.random()*3000)}
document.addEventListener("click",e=>{if(reactReady&&e.target.classList.contains("goBtn")){const ms=Math.round(performance.now()-reactStart);saveHigh("reaction",ms,true);document.getElementById("reactionResult").innerHTML='<strong>⚡ '+ms+' ms</strong>'+highText("reaction"," ms")+'<br><button onclick="reaction()">Nochmal</button>';reactReady=false}});
let spaceRun;
function space(){const b=document.getElementById("spaceBox");b.innerHTML='<div id="ship">🚀</div><div class="score" id="spaceScore">Score: 0</div><div class="spaceControls"><button data-dir="left">◀</button><button data-dir="right">▶</button></div>';const ship=b.querySelector("#ship");let score=0,x=50;function move(dir){x=dir==="left"?Math.max(8,x-8):Math.min(92,x+8);ship.style.left=x+"%"}b.querySelector('[data-dir="left"]').addEventListener("pointerdown",()=>move("left"));b.querySelector('[data-dir="right"]').addEventListener("pointerdown",()=>move("right"));document.onkeydown=e=>{if(e.key==="ArrowLeft")move("left");if(e.key==="ArrowRight")move("right")};clearInterval(spaceRun);spaceRun=setInterval(()=>{score++;document.getElementById("spaceScore").textContent="Score: "+score;if(score>=30){clearInterval(spaceRun);saveHigh("space",score);b.innerHTML='<strong>🏆 Überlebt! Score '+score+'</strong>'+highText("space","")+'<br><button onclick="space()">Nochmal</button>'}},1000)}
function memory(){const r=document.getElementById("memoryResult");const a=["🍎","🚀","⭐","🐱","🍎","🚀","⭐","🐱"].sort(()=>Math.random()-.5);let open=[],done=0;r.innerHTML="";a.forEach(v=>{const b=document.createElement("button");b.className="memoryCard";b.textContent="❓";b.onclick=()=>{if(open.length>=2||b.dataset.done)return;b.textContent=v;open.push([b,v]);if(open.length===2){if(open[0][1]===open[1][1]){open.forEach(x=>x[0].dataset.done=1);done+=2;open=[];if(done===8)r.insertAdjacentHTML("beforeend",'<p>🏆 Geschafft!</p>'+highText("memory",""))}else setTimeout(()=>{open.forEach(x=>x[0].textContent="❓");open=[]},600)}};r.appendChild(b)})}
function aim(){const b=document.getElementById("aimBox");let n=0,start=performance.now();b.innerHTML='<div id="target"></div><div class="score" id="aimScore">0 / 10</div>';function next(){const t=document.getElementById("target");if(!t)return;t.style.left=Math.random()*78+"%";t.style.top=Math.random()*58+"%";t.onclick=()=>{n++;document.getElementById("aimScore").textContent=n+" / 10";if(n>=10){const sec=((performance.now()-start)/1000).toFixed(3);saveHigh("aim",Number(sec),true);b.innerHTML='<strong>🎯 '+sec+' s</strong>'+highText("aim"," s")+'<br><button onclick="aim()">Nochmal</button>'}else next()}}next()}
let planeFrame,planeScore=0,planeY=50,planeAlive=false;
function flappy(){const b=document.getElementById("flappyBox");clearInterval(planeFrame);planeScore=0;planeY=50;planeAlive=true;b.innerHTML='<div class="flappyScore" id="flappyScore">Score: 0</div><div id="plane">✈️</div><div class="flappyHint">Tippen = hoch</div>';const plane=b.querySelector("#plane");let velocity=0,obstacles=[],last=performance.now(),spawn=0;
function flap(){if(planeAlive)velocity=-7}b.onpointerdown=flap;document.onkeydown=e=>{if(e.code==="Space"||e.key==="ArrowUp"){e.preventDefault();flap()}};function end(){planeAlive=false;clearInterval(planeFrame);saveHigh("flappy",planeScore);b.innerHTML='<strong>💥 Game Over – Score '+planeScore+'</strong>'+highText("flappy","")+'<br><button onclick="flappy()">Nochmal</button>'}
planeFrame=setInterval(()=>{const now=performance.now(),dt=Math.min((now-last)/16,2);last=now;velocity+=0.42*dt;planeY+=velocity*dt;if(planeY<5||planeY>92)return end();plane.style.top=planeY+"%";spawn-=dt;if(spawn<=0){spawn=65;const gap=42+Math.random()*8,gapTop=10+Math.random()*(78-gap);const top=document.createElement("div"),bottom=document.createElement("div");top.className=bottom.className="pipe";top.style.height=gapTop+"%";bottom.style.height=(100-gapTop-gap)+"%";bottom.style.bottom="0";bottom.style.top="auto";b.append(top,bottom);obstacles.push({top,bottom,x:100,passed:false})}obstacles.forEach(o=>{o.x-=0.9*dt;o.top.style.left=o.bottom.style.left=o.x+"%";const px=plane.offsetLeft,py=plane.offsetTop,pw=plane.offsetWidth,ph=plane.offsetHeight;const ox=o.top.offsetLeft,ow=o.top.offsetWidth;if(ox<px+pw&&ox+ow>px){const gapTopH=o.top.offsetHeight,gapBottomY=o.bottom.offsetTop;if(py<gapTopH||py+ph>gapBottomY)return end()}if(!o.passed&&o.x<0){o.passed=true;planeScore++;document.getElementById("flappyScore").textContent="Score: "+planeScore}});obstacles=obstacles.filter(o=>o.x>-12)},16)}

let raceRun;
function racing(){const b=document.getElementById("racingBox");clearInterval(raceRun);b.innerHTML='<div class="raceScore" id="raceScore">Score: 0</div><div id="road"><div id="car">🏎️</div><div class="roadLine l1"></div><div class="roadLine l2"></div></div><div class="raceControls"><button data-race="left">◀</button><button data-race="right">▶</button></div>';let x=50,score=0,alive=true,obs=[];const car=b.querySelector("#car");function move(d){x=d==="left"?Math.max(12,x-12):Math.min(88,x+12);car.style.left=x+"%"}b.querySelector('[data-race="left"]').onpointerdown=()=>move("left");b.querySelector('[data-race="right"]').onpointerdown=()=>move("right");document.onkeydown=e=>{if(e.key==="ArrowLeft")move("left");if(e.key==="ArrowRight")move("right")};function end(){alive=false;clearInterval(raceRun);saveHigh("racing",score);b.innerHTML='<strong>🏁 Unfall! Score '+score+'</strong>'+highText("racing","")+'<br><button onclick="racing()">Nochmal</button>'}let tick=0;raceRun=setInterval(()=>{if(!alive)return;tick++;if(tick%28===0){const o=document.createElement("div");o.className="raceObstacle";o.textContent="🚗";o.style.left=(15+Math.random()*70)+"%";o.style.top="-12%";b.querySelector("#road").appendChild(o);obs.push(o)}obs.forEach(o=>{o.style.top=(parseFloat(o.style.top)+1.7)+"%";const ox=parseFloat(o.style.left),oy=parseFloat(o.style.top);if(oy>72&&oy<92&&Math.abs(ox-x)<12)return end()});obs=obs.filter(o=>{if(parseFloat(o.style.top)>105){o.remove();score++;document.getElementById("raceScore").textContent="Score: "+score;return false}return true})},50)}
let pongRun;
function pong(){const b=document.getElementById("pongBox");clearInterval(pongRun);b.innerHTML='<div class="pongScore" id="pongScore">0 : 0</div><div id="pongField"><div id="pongPlayer"></div><div id="pongCpu"></div><div id="pongBall"></div></div><div class="pongControls"><button data-pong="left">▲</button><button data-pong="right">▼</button></div>';let py=42,cy=42,ballX=50,ballY=50,vx=.55,vy=.45,ps=0,cs=0;const field=b.querySelector("#pongField"),player=b.querySelector("#pongPlayer"),cpu=b.querySelector("#pongCpu"),ball=b.querySelector("#pongBall");function playerMove(d){py=Math.max(5,Math.min(80,py+d));player.style.top=py+"%"}b.querySelector('[data-pong="left"]').onpointerdown=()=>playerMove(-8);b.querySelector('[data-pong="right"]').onpointerdown=()=>playerMove(8);document.onkeydown=e=>{if(e.key==="ArrowUp")playerMove(-5);if(e.key==="ArrowDown")playerMove(5)};pongRun=setInterval(()=>{ballX+=vx;ballY+=vy;cy+=(ballY-cy)*.045;if(ballY<3||ballY>94)vy*=-1;if(ballX<8&&ballY>py-5&&ballY<py+25){vx=Math.abs(vx)+.02;ballX=8}if(ballX>88&&ballY>cy-5&&ballY<cy+25){vx=-Math.abs(vx)-.02;ballX=88}if(ballX<0){cs++;ballX=50;ballY=50;vx=.55}if(ballX>100){ps++;ballX=50;ballY=50;vx=-.55}player.style.top=py+"%";cpu.style.top=cy+"%";ball.style.left=ballX+"%";ball.style.top=ballY+"%";document.getElementById("pongScore").textContent=ps+" : "+cs;if(ps>=5||cs>=5){clearInterval(pongRun);saveHigh("pong",ps);b.innerHTML='<strong>🏓 '+(ps>cs?'Du gewinnst!':'Computer gewinnt!')+' '+ps+' : '+cs+'</strong>'+highText("pong"," Punkte")+'<br><button onclick="pong()">Nochmal</button>'}},30)}

let flightFrame,flightActive=false;
function flight3d(){const b=document.getElementById("flight3dBox");if(flightFrame)cancelAnimationFrame(flightFrame);b.innerHTML='<canvas id="flightCanvas"></canvas><div class="flightScore" id="flightScore">Score: 0</div><div class="flightControls"><button data-f="left">◀</button><button data-f="up">▲</button><button data-f="down">▼</button><button data-f="right">▶</button></div>';const c=b.querySelector("#flightCanvas"),ctx=c.getContext("2d");let w=0,h=0,x=0,y=0,score=0,z=0,objects=[],last=performance.now();flightActive=true;
function resize(){const r=b.getBoundingClientRect();w=Math.max(320,Math.floor(r.width));h=240;c.width=w*devicePixelRatio;c.height=h*devicePixelRatio;c.style.width=w+"px";c.style.height=h+"px";ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}resize();
function steer(dx,dy){x=Math.max(-1,Math.min(1,x+dx));y=Math.max(-.8,Math.min(.8,y+dy))}
b.querySelector('[data-f="left"]').onpointerdown=()=>steer(-.14,0);b.querySelector('[data-f="right"]').onpointerdown=()=>steer(.14,0);b.querySelector('[data-f="up"]').onpointerdown=()=>steer(0,-.12);b.querySelector('[data-f="down"]').onpointerdown=()=>steer(0,.12);
document.onkeydown=e=>{if(e.key==="ArrowLeft")steer(-.08,0);if(e.key==="ArrowRight")steer(.08,0);if(e.key==="ArrowUp")steer(0,-.07);if(e.key==="ArrowDown")steer(0,.07)};
for(let i=0;i<9;i++)objects.push({z:i*1.8+2,ox:(Math.random()*2-1)*.75,oy:(Math.random()*2-1)*.6,type:i%3});
function clearAnimationFrame(){if(flightFrame)cancelAnimationFrame(flightFrame)}
function endFlight(){flightActive=false;clearAnimationFrame();saveHigh("flight3d",score);b.innerHTML='<strong>💥 Flug beendet – Score '+score+'</strong>'+highText("flight3d","")+'<br><button onclick="flight3d()">Nochmal</button>'}
function loop(now){if(!flightActive)return;const dt=Math.min((now-last)/16,2);last=now;z+=.035*dt;ctx.clearRect(0,0,w,h);
let grd=ctx.createLinearGradient(0,0,0,h);grd.addColorStop(0,"#172b50");grd.addColorStop(.55,"#5d87ad");grd.addColorStop(.56,"#46543c");grd.addColorStop(1,"#172516");ctx.fillStyle=grd;ctx.fillRect(0,0,w,h);
ctx.strokeStyle="rgba(255,255,255,.25)";ctx.lineWidth=2;for(let i=1;i<7;i++){let yy=h*.56+(i*i)*5;ctx.beginPath();ctx.moveTo(0,yy);ctx.lineTo(w,yy);ctx.stroke()}
objects.forEach(o=>{o.z-=.045*dt;if(o.z<.35){o.z+=16;o.ox=(Math.random()*2-1)*.8;o.oy=(Math.random()*2-1)*.65;o.type=Math.floor(Math.random()*3);score++;b.querySelector("#flightScore").textContent="Score: "+score}
const p=1/o.z,px=w/2+(o.ox-x)*w*.48*p,py=h*.56+(o.oy-y)*h*.45*p,s=Math.min(120,260*p);ctx.save();ctx.translate(px,py);
if(o.type===0){ctx.strokeStyle="#fff";ctx.lineWidth=Math.max(2,s*.08);ctx.beginPath();ctx.arc(0,0,s,s*.65,0,Math.PI*2);ctx.stroke()}else if(o.type===1){ctx.fillStyle="#222";ctx.fillRect(-s*.45,-s*.45,s*.9,s*.9);ctx.fillStyle="#777";ctx.fillRect(-s*.25,-s*.6,s*.5,s*.2)}else{ctx.fillStyle="#ddd";ctx.beginPath();ctx.moveTo(0,-s*.5);ctx.lineTo(s*.5,s*.5);ctx.lineTo(0,s*.25);ctx.lineTo(-s*.5,s*.5);ctx.closePath();ctx.fill()}ctx.restore();
if(o.z<.8&&Math.abs(o.ox-x)<.22&&Math.abs(o.oy-y)<.2)return endFlight()});
ctx.save();ctx.translate(w/2,h*.86);ctx.fillStyle="#eee";ctx.beginPath();ctx.moveTo(0,-28);ctx.lineTo(8,18);ctx.lineTo(65,28);ctx.lineTo(12,4);ctx.lineTo(0,12);ctx.lineTo(-12,4);ctx.lineTo(-65,28);ctx.lineTo(-8,18);ctx.closePath();ctx.fill();ctx.restore();
flightFrame=requestAnimationFrame(loop)}flightFrame=requestAnimationFrame(loop)}
